name:                adventofcode
github:              "mankalas/adventofcode"
author:              "Vincent boucheny"
maintainer:          "mankalas@gmail.com"

dependencies:
- base >= 4.10 && < 5

library:
  dependencies:
    - common
    - aoc2015
    - aoc2017
    - aoc2021

tests:
  haskell-test:
    dependencies:
      - common
      - aoc2015
      - aoc2017
      - aoc2021
