name: aoc2015

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-type-defaults
  - -fno-warn-unused-do-bind
  - -fwarn-tabs
dependencies:
  - base >= 4.10 && < 5
  - containers
  - common
  - tasty
  - tasty-hunit
  - HUnit
  - parsec
  - pureMD5
  - bytestring

library:
  source-dirs: src

tests:
  day01:
    main: test/Day01Spec.hs
    dependencies:
      - aoc2015

  day02:
    main: test/Day02Spec.hs
    dependencies:
      - aoc2015

  day03:
    main: test/Day03Spec.hs
    dependencies:
      - aoc2015


  day04:
    main: test/Day04Spec.hs
    dependencies:
      - aoc2015
