name: aoc2017

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-type-defaults
  - -fno-warn-unused-do-bind
  - -fwarn-tabs
dependencies:
  - base >= 4.10 && < 5
  - common
  - split
  - containers
  - parsec
  - vector
  - vector-split
  - either-unwrap
  - tasty
  - tasty-hunit


library:
  source-dirs: src

tests:
  day01:
    main: test/Day01Spec.hs
    dependencies:
      - aoc2017
