name: common

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fno-warn-type-defaults
dependencies:
  - base >= 4.10
  - array

library:
  source-dirs: src
  dependencies:
    - split
    - containers
    - vector
    - vector-split
    - parsec
    - either-unwrap
    - tasty
    - tasty-hunit
    - HUnit

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - common
      - tasty
      - tasty-hunit
      - HUnit
      - vector
