name:                haskell
version:             0.1.0.0
github:              "mankalas/adventofcode"
license:             BSD3
author:              "Vincent boucheny"
maintainer:          "mankalas@gmail.com"
copyright:           "2017 Vincent Boucheny"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskell#readme>

dependencies:
- base >= 4.10 && < 5

DEFAULT_EXE_OPTIONS: &DEFAULT_EXE_OPTIONS
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - haskell
    - tasty
    - tasty-hunit
    - HUnit

library:
  source-dirs: src
  dependencies:
    - split
    - containers
    - Unique
    - vector
    - vector-split
    - parsec
    - either-unwrap

executables:
  haskell-exe:
    <<: *DEFAULT_EXE_OPTIONS
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - haskell

tests:
  haskell-test:
    <<: *DEFAULT_EXE_OPTIONS
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - vector

  day01:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day01_spec.hs
    source-dirs: test/day01
