name:                haskell
version:             0.1.0.0
github:              "mankalas/adventofcode"
license:             BSD3
author:              "Vincent boucheny"
maintainer:          "mankalas@gmail.com"
copyright:           "2017 Vincent Boucheny"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskell#readme>

dependencies:
- base >= 4.10 && < 5

DEFAULT_EXE_OPTIONS: &DEFAULT_EXE_OPTIONS
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - haskell
    - tasty
    - tasty-hunit
    - HUnit

library:
  source-dirs: src
  dependencies:
    - split
    - containers
    - Unique
    - vector
    - vector-split
    - parsec
    - either-unwrap

executables:
  haskell-exe:
    <<: *DEFAULT_EXE_OPTIONS
    main:                Main.hs
    source-dirs:         app

tests:
  day01:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day01_spec.hs
    source-dirs:
      - test/day01
      - test

  day02:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day02_spec.hs
    source-dirs:
      - test/day02
      - test

  day03:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day03_spec.hs
    source-dirs:
      - test/day03
      - test

  day04:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day04_spec.hs
    source-dirs:
      - test/day04
      - test

  day05:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day05_spec.hs
    source-dirs:
      - test/day05
      - test

  day06:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day06_spec.hs
    source-dirs:
      - test/day06
      - test

  day07:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day07_spec.hs
    source-dirs:
      - test/day07
      - test

  day08:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day08_spec.hs
    source-dirs:
      - test/day08
      - test

  day09:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day09_spec.hs
    source-dirs:
      - test/day09
      - test

  day10:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day10_spec.hs
    source-dirs:
      - test/day10
      - test

  day11:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day11_spec.hs
    source-dirs:
      - test/day11
      - test

  day12:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day12_spec.hs
    source-dirs:
      - test/day12
      - test

  day13:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day13_spec.hs
    source-dirs:
      - test/day13
      - test

  day14:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day14_spec.hs
    source-dirs:
      - test/day14
      - test

  day15:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day15_spec.hs
    source-dirs:
      - test/day15
      - test

  day16:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day16_spec.hs
    source-dirs:
      - test/day16
      - test

  day17:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day17_spec.hs
    source-dirs:
      - test/day17
      - test

  day18:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day18_spec.hs
    source-dirs:
      - test/day18
      - test

  day19:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day19_spec.hs
    source-dirs:
      - test/day19
      - test

  day20:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day20_spec.hs
    source-dirs:
      - test/day20
      - test

  day21:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day21_spec.hs
    source-dirs:
      - test/day21
      - test

  day22:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day22_spec.hs
    source-dirs:
      - test/day22
      - test

  day23:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day23_spec.hs
    source-dirs:
      - test/day23
      - test

  day24:
    <<: *DEFAULT_EXE_OPTIONS
    main: Day24_spec.hs
    source-dirs:
      - test/day24
      - test
